version: '3.11'

services:
  user_service:
    build: ./user_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./user_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
      - FILE_SERVICE_HOST_URL=http://file_service:8000/api/v1/files/

  user_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev

  file_service:
    build: ./file_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./file_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://file_db_username:file_db_password@file_db/file_db_dev

  file_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_file:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=file_db_username
      - POSTGRES_PASSWORD=file_db_password
      - POSTGRES_DB=file_db_dev
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - file_service
      - user_service

volumes:
  postgres_data_user:
  postgres_data_file: